# Generated by Django 4.0 on 2022-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
