# Generated by Django 4.0 on 2022-02-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
