# Generated by Django 4.0 on 2022-01-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=20)),
                ('doc', models.CharField(max_length=20)),
                ('doc_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
