# Generated by Django 4.0 on 2022-01-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='doc',
            field=models.CharField(choices=[('pan', 'PAN Card '), ('aadhar', 'AAdhar Card')], max_length=20),
        ),
    ]
