# Generated by Django 4.0 on 2022-01-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
